# Use an official nginx image as the base image
FROM nginx:alpine

# Copy the static files to the nginx html directory
COPY todo6.html /usr/share/nginx/html/index.html
COPY todo6.css /usr/share/nginx/html/
COPY todo6.js /usr/share/nginx/html/

# Expose the port on which nginx is running
EXPOSE 80

# Start nginx using JSON array syntax
CMD ["nginx", "-g", "daemon off;"]

# Use an official nginx image as the base image
#FROM nginx:alpine

# Copy the static files to the nginx html directory
#COPY todo6.html /usr/share/nginx/html/index.html
#COPY todo6.css /usr/share/nginx/html/
#COPY todo6.js /usr/share/nginx/html/

# Expose the port on which nginx is running
#EXPOSE 80

# Start nginx using JSON array syntax
#CMD ["nginx", "-g", "daemon off;"]
