FROM nginx:alpine
COPY traffic-light.html /usr/share/nginx/html/index.html
COPY traffic-light.css /usr/share/nginx/html/
COPY traffic-light.js /usr/share/nginx/html/

EXPOSE 80

#CMD ["nginx", "-g", "dameon off;"]

CMD ["nginx", "-g", "daemon off;"]
