FROM nginx:alpine

COPY  season-switcher.html /usr/share/nginx/html/index.html
COPY season-switcher.css /usr/share/nginx/html/
COPY season-switcher.js /usr/share/nginx/html/

EXPOSE 80

#CMD [ "nginx" "-g" "dameon off;" ]
CMD ["nginx", "-g", "daemon off;"]

